### ISSUE TITLE
from datasets.vcoco import vsrl_utils as vu，The file vcoco.py does not exist in the directory datasets

### ISSUE THREAD

**Issue by wannning** [birlrobotics/vs-gats#2]
from datasets.vcoco import vsrl_utils as vu
ModuleNotFoundError: No module named 'datasets.vcoco'

**Comment by BIGJUN777** [comment]
Hello,

This module is the same as [v-coco](https://github.com/s-gupta/v-coco). You need to clone it by yourself.
