### ISSUE TITLE
About Test with my own pictures and visualize the result

### ISSUE THREAD

**Issue by YaoDongAn** [birlrobotics/vs-gats#3]
Hi, BIGJUN777. 

Vs-gats is a exciting work. I am very interested in your work. After finishing running hico_eval.py,  I can't find the .py file to visualize the results of HOI detection. It seems that the vis_tool.py can only work  with specific picture. Can you nicely tell me how to test vs-gats with my own pictures  and  visualize the result ? 

Thank you very much.

**Comment by BIGJUN777** [comment]
Hello, 

Thank you for your attention to our work. For visualization on the testing images of HICO-DET or V-COCO, you can refer to the _inference.py_ file. Before running, I think you should reset the [path](https://github.com/birlrobotics/vs-gats/blob/850cce6c0bc3f826351e7a5c9d8cf223649ee9a0/inference.py#L62) to the testing images. As for testing on your own data or running the code in real-time, you can refer to _datasets/hico_process.sh_ to prepare the data. It may be a little bit complex when using those codes, but we will consider doing real-time detection in the future.

**Comment by YaoDongAn** [comment]
Hello，

Thank you for your reply. I'll follow your guidance and take a try. Hope you have a nice day!
