### ISSUE TITLE
About use the network on self-made datasets

### ISSUE THREAD

**Issue by YaoDongAn** [birlrobotics/vs-gats#4]
Hi @BIGJUN777 ,

When I try to test your network on my self-made datasets, I encounter a trouble:my datasets' **object classification** are very different with HICO and V-coco datasets. Do I need to train a new object detector?

May I ask your suggestion about it?

**Comment by BIGJUN777** [comment]
Hi, 

- Please note that we just leveraged the Faster-RCNN pretrained on COCO in our experiments. That is to say we did not fine-tune the object detector on HICO-DET as well as V-COCO. 
-  Recently, more and more works have proved that fine-tuning the object detector on the target dataset would significantly facilitate HOI detection. 
- The object category in HICO-DET and V-COCO is the same as those in COCO (_80 classes_). If your dataset contains some object classes which do not exist in COCO, you should train the object detector in your own dataset. Moreover, you should retrain or fine-tune our model on your datasets.

**Comment by YaoDongAn** [comment]
Thank you for your generous suggestion!
I will take a try.

**Comment by Radleye** [comment]
> Hi @BIGJUN777 ,
> 
> When I try to test your network on my self-made datasets, I encounter a trouble:my datasets' **object classification** are very different with HICO and V-coco datasets. Do I need to train a new object detector?
> 
> May I ask your suggestion about it?

@YaoDongAn  hello, do you know how to made own datasets. i confused about it ,could you tell something about it,thanks
