### ISSUE TITLE
About training object detector details

### ISSUE THREAD

**Issue by YaoDongAn** [birlrobotics/vs-gats#5]
Hi, BIGJUN777!

Sorry for bothering you again.
I noticed that you have modify the _generalized_rcnn.py_ and _roi_heads.py_ .  So when I using faster_rcnn to train the object detector, I encountered some problems.
`Traceback (most recent call last):
  File "/home/y/PycharmProjects/vs-gats/datasets/hico_train_faster_rcnn.py", line 38, in <module>
    train_one_epoch(model, optimizer, data_loader, device, epoch, print_freq=10)
  File "/home/y/PycharmProjects/vs-gats/datasets/engine.py", line 36, in train_one_epoch
    loss_dict = model(images, targets,save_feat=False)
  File "/home/y/anaconda3/envs/vsga/lib/python3.6/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/y/anaconda3/envs/vsga/lib/python3.6/site-packages/torchvision/models/detection/generalized_rcnn.py", line 64, in forward
    bbox_wst_processed_img = detections[0]['boxes'][:]
IndexError: list index out of range
`
It truns out when fasterrcnn network is training and save_feat==False， the **detections** will not be computed and still be a null list.    The _roi_heads.forward()_will only return **losses**.  so the 
So can I skip executing this line of program and modify the output？And will these changes cause more problems? 

It confused me for a long time, hope you can help.
Thanks anyway!

**Comment by BIGJUN777** [comment]
Hello,
Note that the object detector was frozen in our method and we got the object detection results offline. If you have tried to set "save_feat=False" and it didn't work when training the Faster R-CNN, please leverage the official implementation code of Faster R-CNN in Pytorch for training (I am sorry I have no time to debug it for you in the following days). If you did not backup those two files _generalized_rcnn.py_ and _roi_heads.py_, you can find them [here](https://github.com/pytorch/vision/tree/master/torchvision/models/detection).  And after you get the satisfying detection results on your own dataset, you can leverage the saved checkpoint to initialize the Faster R-CNN [here](https://github.com/birlrobotics/vs-gats/blob/850cce6c0bc3f826351e7a5c9d8cf223649ee9a0/datasets/hico_run_faster_rcnn.py#L19).  

Best regards.
Liang Zhijun

**Comment by YaoDongAn** [comment]
Hi，
Thanks for your reply！It helps me a lot.
I have tried the way you said. And it works. But I don't sure whether it works right.
the output of faster_rcnn contains **boxes, scores and nms_keep_indices（instead of labels）**.
The value of **nms_keep_indices** varies from 0 to 1000 like：
`'labels': [[993, 992, 999, 998, 994, 995, 978, 979, 983, 961, 968, 962, 963, 965, 966, 974, 982, 977, 976, 990, 991, 989, 987, 985, 908, 910, 927, 924, 925, 922, 921, 923, 919, 914, 913, 930, 931, 934, 942, 941, 938, 937, 948, 947, 951, 949, 953, 956, 957, 903, 907, 905, 902, 900, 899, 912, 823, 811, 808, 812, 782, 781, 779, 778, 770, 771, 772, 785, 801, 798, 833, 863, 858, 859, 849, 835, 840, 845, 844, 846, 879, 868, 882, 885, 891, 890, 892, 817, 814, 829, 626, 629, 630, 612, 616, 617, 620, 623, 614, 610, 609, 585, 576, 594, 598, 600, 602, 603, 604, 590, 586, 582, 534, 535, 528, 518, 516, 512, 544, 557, 550, 547, 540, 693, 695, 690, 681, 679, 673, 674, 645, 647, 652, 656, 664, 665, 668, 669, 670, 688, 732, 725, 722, 719, 742, 739, 738, 747, 758, 755, 763, 639, 637, 527, 530, 537, 538, 241, 240, 239, 230, 204, 198, 243, 224, 225, 232, 235, 233, 237, 222, 159, 149, 151, 128, 130, 137, 142, 143, 132, 181, 152, 161, 175, 121, 95, 70, 9, 34, 46, 4, 111, 105,....`
By the way，may I ask what **nms_keep_indices**  means？and how it works in the next step of process？

Big Thanks.
Yao DongAn

**Comment by YaoDongAn** [comment]
Hi, BigJun~
Sorry for the bothering again....and again，
After reading the code completely,  I understood the purpose of the code and the meaning of **nms_keep_indices**. 

And there still a question bothering me. After geting the satisfying detection results on my own dataset,  I  leverage the saved checkpoint to initialize the Faster R-CNN that you offered. However,  I can't  get satisfying boudingbox of object when execute and debug  _hico_select_confident_boxes.py_ .   It makes  me so confused.  Do you have any suggestions for this?

Thank you for your generous help. It means a lot for me.
Best regards.
Yao DongAn

**Comment by YaoDongAn** [comment]
> Hi, BigJun~
> Sorry for the bothering again....and again，
> After reading the code completely, I understood the purpose of the code and the meaning of **nms_keep_indices**.
> 
> And there still a question bothering me. After geting the satisfying detection results on my own dataset, I leverage the saved checkpoint to initialize the Faster R-CNN that you offered. However, I can't get satisfying boudingbox of object when execute and debug _hico_select_confident_boxes.py_ . It makes me so confused. Do you have any suggestions for this?
> 
> Thank you for your generous help. It means a lot for me.
> Best regards.
> Yao DongAn

After reconfigured my fasterrcnn network, It performs better right now! That's a big process for me.
Thank you for your previous suggestions.  
And hope you have a nice weekend!
