### ISSUE TITLE
The pretrained model

### ISSUE THREAD

**Issue by wuyifujia** [birlrobotics/vs-gats#6]
dear sir, could you please share the pretrained model with us again? Beacuse the orignal link has lost. Thank you very much!

**Comment by BIGJUN777** [comment]
Hello,

I checked the shared [links](https://github.com/birlrobotics/vs-gats#testing) again and found they were still available. Please double check. If it doesn't work, leave your email here and I will send the pretrained model by email.

**Comment by wuyifujia** [comment]
Thanks for your answer! So can I say GoogleNews-vectors-negative300.bin.gz is the original data of word2vec? And I use the weight you share with us straightly to inference, then I run the inference.py, but I find some pictures are still the same as before. So I try to train it again, and when I train it, it will happen the following phenomena, coule you please share the idea to how to solve this problem?
![train](https://user-images.githubusercontent.com/75160265/106906681-624d6180-6738-11eb-94d8-c9c6f861b72a.png)

**Comment by BIGJUN777** [comment]
- I am curious about what you said *"but I find some pictures are still the same as before"*. Do you mean some output results are unsatisfactory? If so, maybe you can try to reduce the *score_thresh* in this [line](https://github.com/birlrobotics/vs-gats/blob/850cce6c0bc3f826351e7a5c9d8cf223649ee9a0/inference.py#L131) to get more visualization results. BTW, it's normal that VS-GATs can't handle some situations well.   
- For training, please comment this [line](https://github.com/birlrobotics/vs-gats/blob/850cce6c0bc3f826351e7a5c9d8cf223649ee9a0/hico_train.py#L131) which I forgot to comment. Sorry about that.

**Comment by wuyifujia** [comment]
Thanks very much for your patient answer, I am very grateful fot you, and the problem of trainging has sovled. And the meaning of that word is the result did not has a bounding_box in the image, only a image is the same as the orignal one.

**Comment by BIGJUN777** [comment]
- GoogleNews-vectors-negative300.bin.gz is the pre-trained checkpoints of word2vec model. 
- As for the output result you mentioned above, you can try to reduce the *score_thresh* in this [line](https://github.com/birlrobotics/vs-gats/blob/850cce6c0bc3f826351e7a5c9d8cf223649ee9a0/inference.py#L131). This parameter (*score_thresh*) is designed to filter the visualization detection results, where you can find its usage in this [line](https://github.com/birlrobotics/vs-gats/blob/850cce6c0bc3f826351e7a5c9d8cf223649ee9a0/utils/vis_tool.py#L68).

**Comment by wuyifujia** [comment]
Thank you very much, I have sovled problems above. I am grateful for your help!

Best wishes!
